### ISSUE TITLE
[STUD-31] As a student, I want to be able to edit my personal profile in order to update my information.

### ISSUE THREAD

**Issue by yasfahm** [Airbenders-490/AirbendersFE#10]
**Trigger:**

- The student selects their profile
- The student selects the Gears icon

**Acceptance Criteria:**

- You can only edit your own profile
- You can edit the labels section as they are given to you by your teammates

**Conditions of Success:**

- The changes are saved
- The changed fields are updated and shown to other users as such

**User Acceptance Flow:**

- User clicks on the Gear icon
- User edits personal links
- User edits class taken by clicking on the show/hide icon
- User adds or removes skills

[System Testing](https://drive.google.com/file/d/11fqeONkzE74HS3RrjtLuZrzhprsehxSQ/view?usp=sharing)

**Comment by nuzurie** [comment]
Approved!

**Comment by HakimPoly** [comment]
Approved
