### ISSUE TITLE
[STUD-14] As a student, I want to be able to endorse my peers with their top three qualities to help others find suitable teammates.

### ISSUE THREAD

**Issue by yasfahm** [Airbenders-490/AirbendersFE#11]
**Trigger:**

- A class participant is selected
- The endorsement feature from the chosen participant is selected

**Acceptance Criteria:**

- You can only endorse a participant with which you have formed a team AND from the same course

**Conditions of Success:**

- The teammate’s chosen qualities (3) votes are incremented by 1

**User Acceptance Flow:**

- User navigates to peer's profile
- User clicks on collapsible button
- User selects different qualities
- User clicks on save button

[System Testing](https://drive.google.com/file/d/1HsdXslT4W5grNRefTOz0IhkEhAG5QNUn/view?usp=sharing)

**Comment by nuzurie** [comment]
Approved!

**Comment by HakimPoly** [comment]
Approved
