### ISSUE TITLE
[STUD-106] As a student, I want to be able to view other participant’s profile to see whether they would be a good fit for my team.

### ISSUE THREAD

**Issue by yasfahm** [Airbenders-490/AirbendersFE#12]
**Trigger:**

- A class participant is selected

**Acceptance Criteria:**

- Visiting your own profile allows for the Settings feature
- Visiting another user is only a read-only process
- If you were in a team with a participant, the endorsement feature is available on their profile

**Conditions of Success:**

- The user profile is displayed with all necessary information

**User Acceptance Flow:**

- User searches for a participant in a class
- User clicks on the participant
- User is able to view the other person's profile

[System Testing](https://drive.google.com/file/d/1HsdXslT4W5grNRefTOz0IhkEhAG5QNUn/view?usp=sharing)

**Comment by HakimPoly** [comment]
Approved
