### ISSUE TITLE
[STUD-63] As a student, I want to be navigate through the important sections on the application.

### ISSUE THREAD

**Issue by yasfahm** [Airbenders-490/AirbendersFE#13]
**Acceptance Criteria:**

- The icon for the current page is displayed with a visible cue

**Conditions of Success:**

- Selecting the different icons on the navigation bar redirects the user to the desired page

**User Acceptance Flow:**

- User clicks on graduation cap icon
- User is redirected to Classes screen
------------------------

- User clicks on enveloppe icon
- User is redirected to Messages screen
------------

- User clicks on calendar icon
- User is redirected to Schedule screen
------------

- User clicks on the user icon
- User is redirected to Profile screen
------------

- User clicks on the icon with 3 lines
- User is redirected to their Feed

**Comment by nuzurie** [comment]
Approved!

**Comment by HakimPoly** [comment]
Approved
