### ISSUE TITLE
[EPIC] Initial Setup

### ISSUE THREAD

**Issue by car12lin12** [Airbenders-490/AirbendersFE#17]
As the developer, we want:
- The architecture diagrams at least for the highest priority epics should be complete such that model/domains blueprints can be used to create database tables and at least be used with mock data
    - [STUD 68] Create student database and tables with mock data
- [STUD 64] As a developer, we want the main styling theme to be chosen and reusable components (backgrounds, boxes, buttons...) to be created so that a standardized design can be implemented for further features
- [STUD 63] Initialize Navigation Bar; As a student, I want to navigate through the important sections of the application

**Comment by nuzurie** [comment]
Tested and approved :)
