### ISSUE TITLE
[STUD-28] As a student, I want to be able to send messages to my conversations in order to communicate efficiently.

### ISSUE THREAD

**Issue by yasfahm** [Airbenders-490/AirbendersFE#27]
**Trigger:**
- The user is in an existing conversation

 **Acceptance Criteria:**
- If the text input is empty, disable the Send button

**Conditions of Success:**
- Once the user presses the Send button, the message is displayed onto the conversation
- All members of the conversation (1+) can now view the message

**User Acceptance Flow:** 
- User is on an existing conversation
- User writes a message
- User clicks on send button

**Comment by HakimPoly** [comment]
Approved
