### ISSUE TITLE
[STUD-29] As a student, I want to be able to edit my messages in a conversation to correct mistakes.

### ISSUE THREAD

**Issue by yasfahm** [Airbenders-490/AirbendersFE#28]
**Trigger:**
- The user is in an existing conversation
- The user has sent a message with a mistake

 **Acceptance Criteria:**
- The user can only edit messages they sent themselves
- The user can modify a message by clicking on it and selecting the Modify icon (pencil)

**Conditions of Success:**
- The message is modified
- The modified message is updated to all team members

**User Acceptance Flow:** 
- User is on an existing conversation
- User clicks on a message sent by them
- User clicks on pencil icon
- User types the new message

**Comment by HakimPoly** [comment]
Approved
