### ISSUE TITLE
[STUD-30]  As a student, I want to be able to delete my messages in a conversation in case they are no longer relevant.

### ISSUE THREAD

**Issue by yasfahm** [Airbenders-490/AirbendersFE#29]
**Trigger:**
- The user is in an existing conversation
- The user has sent a message with a mistake

 **Acceptance Criteria:**
- The user can only delete messages they sent themselves
- The user can delete a message by clicking on it and selecting the Delete icon (bin)

**Conditions of Success:**
- The message is deleted
- The deleted message is no longer viewable to all team members

**User Acceptance Flow:** 
- User is on an existing conversation
- User clicks on a message sent by them
- User clicks on delete icon

**Comment by HakimPoly** [comment]
Approved
