### ISSUE TITLE
[STUD-167] As a student, I want to be able to retrieve messages for specific chat rooms so I can read my messages.

### ISSUE THREAD

**Issue by yasfahm** [Airbenders-490/AirbendersFE#30]
**Trigger:**
- The user chooses to view a list of the chat rooms they are currently a part of.

**Acceptance Criteria:**
- The user can read the messages for a chosen chat room.

**Conditions of Success:**
- The user can choose a chat room to open
- The user can view the messages in the chat room they’ve opened

**User Acceptance Flow:** 
- User is on the list of the chat rooms
- User clicks on a chat room 
- User is able to view the conversation

**Comment by HakimPoly** [comment]
Approved
