### ISSUE TITLE
[STUD-199] Perform Usability Tests

### ISSUE THREAD

**Issue by car12lin12** [Airbenders-490/AirbendersFE#33]
As a stakeholder, I want the app to be easy to use ( having at least 50% success rate and 50% error rates ) and have initial usability tests performed on the Login and Profile services for release 2. This task includes choosing a usability tool then performing usability tests on the following tasks:
1. Login using credentials
2. Navigating to the Profile Page
3. Editing the Profile Page

The minimum metrics to use are the Error rates, Success rates and Task Completion time.

**Comment by HakimPoly** [comment]
Approved
