### ISSUE TITLE
[STUD-25]  As a student, I want to join an existing team in a course

### ISSUE THREAD

**Issue by yasfahm** [Airbenders-490/AirbendersFE#54]
**Trigger:**
- The user is on the Class page, under the Teams tab
- They have selected a team and the component has expanded
- They have clicked on the Request to join button

 **Acceptance Criteria:**
- Teams can only be joinable if a spot is available (shown by a visible cue, as well as as the ratio of occupied slots)
- The number of occupied spots in the team’s component does not increment until the student’s request is accepted
- If the request is denied by the team members, the student is no longer found under the team members list

**Conditions of Success:**
- The student now appears as a potential team member (yellow cue)
- By visiting the Teams tab, as well as their teams, team members can confirm or reject the request
- By visiting their team chat, team members can confirm or reject the request under the participants tab

**User Acceptance Flow:** 
- User is on the Class page under Teams tabs
- User selects a team and the component is expanded
- User clicks on Request button

**Comment by HakimPoly** [comment]
Approved
