### ISSUE TITLE
[STUD-228] As a student, I want to see and control the classes I have taken and am currently enrolled in, on my profile.

### ISSUE THREAD

**Issue by yasfahm** [Airbenders-490/AirbendersFE#55]
**Trigger:**
- The user is on the their profile
- They have selected to move a ‘currently enrolled in’ class to ‘completed’ status

**Acceptance Criteria:**
- The selected class is now seen as ‘completed’ and not ‘currently enrolled in’

**Conditions of Success:**
- The student and other app users can see the class as ‘completed’

**Comment by HakimPoly** [comment]
Approved
