### ISSUE TITLE
[STUD-24] As a student, I want to create a team when my team requests have been confirmed.

### ISSUE THREAD

**Issue by yasfahm** [Airbenders-490/AirbendersFE#56]
**Trigger:**
- The users that have received a request for team confirmation have either confirmed or rejected 

**Acceptance Criteria:**
- If the number of confirmations are higher than 1, create team chat for that course
     -  greater than 1 : One confirmation means the team is already at two; current user and student who confirmed

**Conditions of Success:**
- The team now appears in the Teams tab under the Class page
- The existing teams are displayed as a list with the necessary information (team name, number of spots available)
- Expanding the teams allows to see the team members' list as well as a button Request to join
- A team is chat is automatically created to house the current participants who have confirmed the request

**Comment by HakimPoly** [comment]
Approved
