### ISSUE TITLE
[STUD-276] As the product owner, I want the app to be usable and improve throughout several waves of testing, undergo usability testing

### ISSUE THREAD

**Issue by yasfahm** [Airbenders-490/AirbendersFE#57]
As the product owner, I want the app to be usable and improve throughout several waves of testing, undergo usability testing for the following tasks:

**LOGIN**:
Task 1: Enter credentials and click login

**PROFILE:** 
Task 2: Navigate to the Profile page 
Task 3: Edit Profile Page fields to reflect information about yourself, you can put dummy information if you wish

 **SCHEDULE** 
Task 4: Navigate to Schedule tab 
Task 5: explore an other student profile 

**FEED** 
Task 6: Navigate to the feed page 
Task 7: Accept or Deny participant 

**MESSAGE** 
Task 8: Navigate to the message section 
Task 9: toggle between the Peer Chats and Team Chats 
Task 10: Edit the message in the Team chat 
Task 11: check out who is participating in the chat 

**TEAM**
 Task 12: Toggle to the Teams tab

**Comment by HakimPoly** [comment]
Approved
