### ISSUE TITLE
[STUD 219] As a student, I want to be able to access the app from any phone

### ISSUE THREAD

**Issue by car12lin12** [Airbenders-490/AirbendersFE#62]
[STUD219](https://team-1610936365889.atlassian.net/browse/STUD-219) Establish Kubernetes and docker on remote Concordia server, access through domain real.encs.concordia.ca

**Trigger:**
- The user uses any feature of the app

**Acceptance Criteria:**
- All API requests are successfully made through the domain real.encs.concordia.ca

**Conditions of Success:**
- All API requests for the EPICS: Profile, Chat, Auth are successfully made through the domain real.encs.concordia.ca

**Comment by HakimPoly** [comment]
Approved
