### ISSUE TITLE
[STUD 251] As a student, I want to be able to search for students to view their profile

### ISSUE THREAD

**Issue by car12lin12** [Airbenders-490/AirbendersFE#63]
[STUD251](https://team-1610936365889.atlassian.net/browse/STUD-251)
**Trigger:**
- The user chooses to search for student profiles

**Acceptance Criteria:**
- The user can access another user's profile

**Conditions of Success:**
- The user can view another student's profile
- The user can post or edit a review for the other student

**Comment by HakimPoly** [comment]
Approved
