### ISSUE TITLE
Scoped out EPICS

### ISSUE THREAD

**Issue by car12lin12** [Airbenders-490/AirbendersFE#64]
#### Due to insufficient time
Scoped out EPICS:
- When2meet
- Scheduling
- Notifications
- Classes

<html>
<body>
<b style="font-weight:normal;" id="docs-internal-guid-938657ad-7fff-6981-09da-39fbffb31941"><div dir="ltr" style="margin-left:0pt;" align="left">

ID | Epic | Title
-- | -- | --
[STUD-65](https://team-1610936365889.atlassian.net/browse/STUD-65) | When2Meet | Initialize When2Meet
[STUD-20](https://team-1610936365889.atlassian.net/browse/STUD-20) | When2Meet | Default fill based on team members' personal schedule
[STUD-21](https://team-1610936365889.atlassian.net/browse/STUD-21) | When2Meet | Identify availabilities
[STUD-43](https://team-1610936365889.atlassian.net/browse/STUD-43) | Notifications | Define notification settings
[STUD-44](https://team-1610936365889.atlassian.net/browse/STUD-44) | Notifications | Chat Notifications
[STUD-45](https://team-1610936365889.atlassian.net/browse/STUD-45) | Notifications | Schedule notifications
[STUD-46](https://team-1610936365889.atlassian.net/browse/STUD-46) | Notifications | Team formation notifications
[STUD-47](https://team-1610936365889.atlassian.net/browse/STUD-47) | Notifications | Review notification
[STUD-49](https://team-1610936365889.atlassian.net/browse/STUD-49) | Classes | Create Class Forum
[STUD-23](https://team-1610936365889.atlassian.net/browse/STUD-23) | Classes | Create Classes Service
[STUD-56](https://team-1610936365889.atlassian.net/browse/STUD-56) | Classes | Create class chat
[STUD-60](https://team-1610936365889.atlassian.net/browse/STUD-60) | Classes | Join Class Forum
[STUD-34](https://team-1610936365889.atlassian.net/browse/STUD-34) | Classes | Drop Class
[STUD-35](https://team-1610936365889.atlassian.net/browse/STUD-35) | Classes | View Participants In Class
[STUD-40](https://team-1610936365889.atlassian.net/browse/STUD-40) | Classes | Leave Team After Dropping Class
[STUD-50](https://team-1610936365889.atlassian.net/browse/STUD-50) | Scheduling | Enter Schedule Info
[STUD-51](https://team-1610936365889.atlassian.net/browse/STUD-51) | Scheduling | Modify Schedule Info
[STUD-52](https://team-1610936365889.atlassian.net/browse/STUD-52) | Scheduling | Delete Busy slots

</div></b>
</body>
</html>

Merged EPICS:
- ( TeamFormation (only do Join) With Messaging/ChatRoom ) and ( Classes attributes With Profile & Messaging/ChatRoom )

**Comment by HakimPoly** [comment]
I approve the Scoped out Features
