### ISSUE TITLE
[STUD-17] As the application, I want to make sure the current user is a university student.

### ISSUE THREAD

**Issue by yasfahm** [Airbenders-490/AirbendersFE#7]
**Trigger:**

- The user is signed in for the first time
- The user has entered their university email in the respective field in the Create Profile page
- The user has selected the Create Profile button

**Acceptance Criteria:**

- Field mandatory when creating the profile
- Possibility of changing the email once the profile is created

**Conditions of Success:**

- The user receives an email into their university email inbox
- Once the user confirms their status, the student’s profile status is Student Confirmed

[System Testing](https://drive.google.com/file/d/1UDcQq8hK5pBesr2EqQcZUIzAcMWDGuPw/view?usp=sharing)

**Comment by nuzurie** [comment]
Approved

**Comment by HakimPoly** [comment]
Approved

**Comment by HakimPoly** [comment]
Approved

**Comment by HakimPoly** [comment]
Approved
