### ISSUE TITLE
[STUD-53] As a student, I want to be able to login into my account when I open the application to view my personalised feed.

### ISSUE THREAD

**Issue by yasfahm** [Airbenders-490/AirbendersFE#8]
**Trigger:**

- The user opens the app

**Acceptance Criteria:**

- If the email/password combination entered is not correct, display an error message
- If the email is not recognized, display a message for them to register instead

**Conditions of Success:**

- The user is successfully logged in
- The user is redirected to the feed

**User Acceptance Flow:**

- User enters email address
- User enters password
- User clicks on login button

[System Testing](https://drive.google.com/file/d/1gb86oKiAEQwvYEKoTgROugwxluKLeDbZ/view?usp=sharing)

**Comment by nuzurie** [comment]
Approved

**Comment by HakimPoly** [comment]
Approved
