### ISSUE TITLE
[STUD-15] As a student, I want to create my personal profile with my information once I sign in the application for the first time.

### ISSUE THREAD

**Issue by yasfahm** [Airbenders-490/AirbendersFE#9]
**Trigger:**

- The user signs into the application for the first time
- The sign in leads to a new page to create the profile

**Acceptance Criteria:**

- Only direct the user to the profile creation when they are signing in for the first time

**Conditions of Success:**

- The user’s profile is created
- The newly entered information is saved to the user’s account
- The user will no longer be redirected to sign in
- The user will now be able to log in

**User Acceptance Flow:**

- User enters short description
- User enters current program
- User enters up to 3 links (LinkedIn, GitHub, etc)
- User enters school email
- User enter classes taken

[System Testing](https://drive.google.com/file/d/1RIz11aPX1_QyPGXcOX9DVS8cqMt6k7a-/view?usp=sharing)

**Comment by nuzurie** [comment]
Approved

**Comment by HakimPoly** [comment]
Approved
